-- ==================================================================
-- Habit Tracker — database setup
--
-- ⚠️  This file previously contained a frozen copy of migrations
-- 0001–0003 and drifted badly out of date (no habit_logs.status, no
-- freeze_banks, stale streak trigger) — a fresh install from it
-- produced a broken app.
--
-- To set up a database, run the files in supabase/migrations/ in
-- order (0001 → 0008), then supabase/seed.sql. With the Supabase CLI:
--
--     supabase db push        # applies supabase/migrations/*
--     psql "$DB_URL" -f supabase/seed.sql
--
-- Or paste each migration into the SQL editor in ascending order.
-- Do not maintain a combined copy here; it will drift again.
-- ==================================================================
