// ================================================================
// Naked Compound — Brands Database
// Maintained by: NC Research Team · nakedcompound.in
// Last updated: May 2026
//
// HOW TO UPDATE:
//   Prices      → edit price field + update lastChecked date
//   New brand   → copy the schema block below and fill in
//   Amazon URLs → replace url with your actual amzn.to link
//
// VERDICT TIERS:
//   recommended  — 7.5+, documented 3P testing, no major flags
//   acceptable   — 5.5–7.4, limited testing, minor concerns
//   flagged      — documented issues: prop blends, test failures, misleading claims
//   blacklisted  — fraud, lab failures, dangerous products
//
// SCORE DIMENSIONS (each 0–10):
//   labelAccuracy   — label claims vs independently tested reality
//   dosing          — clinically validated dose ranges provided
//   fssai           — FSSAI licensing, compliance, documentation
//   thirdParty      — independence + quality of testing (blind-purchase > brand-commissioned)
//   value           — rupee value vs category competition
//
// FLAG KEYS:
//   prop-blend | underdosed | generic-extract | no-coa | label-inflation
//   premium-price | marketing-heavy | legal-issues | brand-coa-only
//   misleading-claims | historical-test-failure | limited-india-testing | no-fssai-confirmed
// ================================================================

const BRANDS_DB = [

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // RECOMMENDED
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'as-it-is',
    name: 'AS-IT-IS Nutrition',
    mark: 'AI',
    markClass: 'mk-green',
    logo: null,
    country: 'India',
    hq: 'Bengaluru',
    since: 2016,
    categories: ['protein','creatine','amino','vitamins','minerals'],
    verdict: 'recommended',
    trustScore: 8.6,
    scores: { labelAccuracy: 9, dosing: 8, fssai: 9, thirdParty: 9, value: 9 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Raw ingredient positioning — minimal additives, unflavoured.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'NABL-accredited (Eurofins India). Trustified-listed. Batch COAs published.',
    flags: [],
    products: [
      { name: 'Whey Protein Concentrate 80%', unit: '1 kg', price: 1999, url: 'https://www.amazon.in/s?k=as+it+is+nutrition+whey+protein+concentrate', lastChecked: 'May 2026' },
      { name: 'Creatine Monohydrate', unit: '500 g', price: 699, url: 'https://www.amazon.in/s?k=as+it+is+nutrition+creatine+monohydrate', lastChecked: 'May 2026' },
      { name: 'BCAA 2:1:1 Powder', unit: '400 g', price: 1199, url: 'https://www.amazon.in/s?k=as+it+is+nutrition+bcaa', lastChecked: 'May 2026' },
    ],
    summary: "India's gold standard for raw ingredient transparency. No flavouring, no additives, multiple NABL COAs on record. Best price-per-gram on domestic WPC80 and creatine monohydrate.",
    reviewUrl: null,
    addedDate: '2026-03',
  },

  {
    id: 'nakpro',
    name: 'Nakpro',
    mark: 'NP',
    markClass: 'mk-green',
    logo: 'logos/nakpro.avif',
    country: 'India',
    hq: 'Bengaluru',
    since: 2018,
    categories: ['protein'],
    verdict: 'recommended',
    trustScore: 8.2,
    scores: { labelAccuracy: 9, dosing: 8, fssai: 9, thirdParty: 9, value: 8 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Food-grade manufacturing, transparent ingredient sourcing.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'Eurofins India (NABL-accredited) via Trustified. Protein quantity + amino acid profile verified.',
    flags: [],
    products: [
      { name: 'Gold Whey Protein', unit: '1 kg', price: 2099, url: 'https://www.amazon.in/s?k=nakpro+gold+whey+protein', lastChecked: 'May 2026' },
      { name: 'Platinum WPI 90%', unit: '1 kg', price: 2799, url: 'https://www.amazon.in/s?k=nakpro+platinum+whey+protein', lastChecked: 'May 2026' },
    ],
    summary: "Eurofins-verified via Trustified for protein content and full amino acid profile. Consistently hits label claims. Note: 'Gold' is a concentrate blend — not a whey isolate, despite the name.",
    reviewUrl: '/reviews/wheyprotein/nakpro-gold-whey-review',
    brandPageUrl: '/brands/nakpro',
    addedDate: '2026-03',
  },

  {
    id: 'optimum-nutrition',
    name: 'Optimum Nutrition',
    mark: 'ON',
    markClass: 'mk-blue',
    logo: 'logos/optimum-nutrition.jpg',
    country: 'USA',
    hq: 'Downers Grove, IL',
    since: 1986,
    categories: ['protein','amino','creatine','vitamins'],
    verdict: 'recommended',
    trustScore: 8.0,
    scores: { labelAccuracy: 9, dosing: 8, fssai: 8, thirdParty: 9, value: 6 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant. Sold via ON-authorized Indian distributors.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'Informed Choice UK. NSF Certified for Sport (select SKUs). Unbox Health A+ (GS Whey).',
    flags: ['premium-price'],
    products: [
      { name: 'Gold Standard 100% Whey', unit: '2 lb', price: 3399, url: 'https://www.amazon.in/s?k=optimum+nutrition+gold+standard+whey', lastChecked: 'May 2026' },
      { name: 'Micronized Creatine Powder', unit: '317 g', price: 1399, url: 'https://www.amazon.in/s?k=on+optimum+nutrition+creatine', lastChecked: 'May 2026' },
    ],
    summary: 'Category-defining product with the strongest 3P certification stack on the India market. Counterfeit risk is real — buy only via Flipkart or ON India authorized channel. Premium pricing is the only objection.',
    reviewUrl: '/reviews/wheyprotein/on-gold-standard-whey-review',
    brandPageUrl: '/brands/optimum-nutrition',
    addedDate: '2026-03',
  },

  {
    id: 'muscleblaze',
    name: 'MuscleBlaze',
    mark: 'MB',
    markClass: 'mk-blue',
    logo: 'logos/muscleblaze.svg',
    logoKey: 'muscleblaze.svg',
    country: 'India',
    hq: 'Gurgaon',
    since: 2012,
    categories: ['protein','creatine','preworkout','vitamins','amino'],
    verdict: 'recommended',
    trustScore: 7.8,
    scores: { labelAccuracy: 8, dosing: 7, fssai: 9, thirdParty: 7, value: 8 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. HealthKart subsidiary. India-manufactured with domestic NABL testing.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'Brand-commissioned NABL labs (Eurofins). Trustified certified on select SKUs. Verify per product.',
    flags: [],
    products: [
      { name: 'Biozyme Performance Whey', unit: '1 kg', price: 2799, url: 'https://www.amazon.in/s?k=muscleblaze+biozyme+performance+whey', lastChecked: 'May 2026' },
      { name: 'Creatine Monohydrate', unit: '500 g', price: 849, url: 'https://www.amazon.in/s?k=muscleblaze+creatine+monohydrate', lastChecked: 'May 2026' },
    ],
    summary: "India's highest-volume supplement brand. Biozyme enzyme complex differentiates from generic WPC. Trustified certification exists for some SKUs — check the specific product before purchasing.",
    reviewUrl: null,
    addedDate: '2026-03',
  },

  {
    id: 'now-foods',
    name: 'NOW Foods',
    mark: 'NF',
    markClass: 'mk-green',
    logo: 'logos/now-foods.svg',
    logoKey: 'now-foods.svg',
    country: 'USA',
    hq: 'Bloomingdale, IL',
    since: 1968,
    categories: ['vitamins','minerals','omega3','herbs','amino'],
    verdict: 'recommended',
    trustScore: 7.8,
    scores: { labelAccuracy: 8, dosing: 8, fssai: 8, thirdParty: 8, value: 8 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant. NSF GMP-registered manufacturing facility.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'NSF GMP registration. In-house + external verification. COAs available on request.',
    flags: [],
    products: [
      { name: 'Vitamin D3 5,000 IU', unit: '360 softgels', price: 1199, url: 'https://www.amazon.in/s?k=now+foods+vitamin+d3+5000', lastChecked: 'May 2026' },
      { name: 'Zinc Gluconate 50 mg', unit: '250 tabs', price: 899, url: 'https://www.amazon.in/s?k=now+foods+zinc+gluconate', lastChecked: 'May 2026' },
      { name: 'Omega-3 Fish Oil 1,000 mg', unit: '200 softgels', price: 1299, url: 'https://www.amazon.in/s?k=now+foods+omega+3+fish+oil', lastChecked: 'May 2026' },
    ],
    summary: "Long-standing GMP-certified brand with the broadest verified range in India's import segment. D3 5,000 IU is exceptional value for India's high deficiency burden. Omega-3 provides actual EPA+DHA — not ALA.",
    reviewUrl: null,
    addedDate: '2026-03',
  },

  {
    id: 'unived',
    name: 'Unived',
    mark: 'UV',
    markClass: 'mk-green',
    logo: 'logos/unived.webp',
    country: 'India',
    hq: 'Bengaluru',
    since: 2014,
    categories: ['vitamins','omega3','protein','minerals'],
    verdict: 'recommended',
    trustScore: 7.6,
    scores: { labelAccuracy: 8, dosing: 8, fssai: 9, thirdParty: 7, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Plant-based / vegan-certified product line.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'NABL-accredited lab testing. Transparent ingredient sourcing with supplier disclosure.',
    flags: [],
    products: [
      { name: 'D3 + K2 (Vegan)', unit: '60 caps', price: 899, url: 'https://www.amazon.in/s?k=unived+vitamin+d3+k2+vegan', lastChecked: 'May 2026' },
      { name: 'Algae Omega-3 EPA+DHA', unit: '60 caps', price: 1299, url: 'https://www.amazon.in/s?k=unived+vegan+omega+3+algae', lastChecked: 'May 2026' },
    ],
    summary: "Best vegan supplement brand in India. Algae-sourced EPA+DHA is the clinically correct omega-3 choice for vegetarians — not flaxseed ALA-only products. D3+K2 uses correct forms at adequate doses.",
    reviewUrl: null,
    addedDate: '2026-03',
  },

  {
    id: 'steadfast',
    name: 'Steadfast Nutrition',
    mark: 'SN',
    markClass: 'mk-green',
    logo: 'logos/steadfast.avif',
    country: 'India',
    hq: 'New Delhi',
    since: 2017,
    categories: ['protein','amino','vitamins','minerals'],
    verdict: 'recommended',
    trustScore: 7.6,
    scores: { labelAccuracy: 8, dosing: 8, fssai: 9, thirdParty: 7, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Clinical-grade positioning with clean, accurate labels.',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'Brand-commissioned NABL labs. Certificates of Analysis published per batch.',
    flags: [],
    products: [
      { name: 'Whey Protein (25 sachets)', unit: '25 × 33 g', price: 2499, url: 'https://www.amazon.in/s?k=steadfast+nutrition+whey+protein+sachets', lastChecked: 'May 2026' },
      { name: 'Magnesium (Glycinate)', unit: '60 caps', price: 999, url: 'https://www.amazon.in/s?k=steadfast+nutrition+magnesium', lastChecked: 'May 2026' },
    ],
    summary: 'Clean-label Indian brand with genuine clinical positioning and batch COAs. Sachet format is expensive per gram but useful for travel and portion control. Strong FSSAI compliance record.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // ACCEPTABLE
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'dymatize',
    name: 'Dymatize',
    mark: 'DZ',
    markClass: 'mk-blue',
    country: 'USA',
    hq: 'Dallas, TX',
    since: 1994,
    categories: ['protein','amino','preworkout'],
    verdict: 'acceptable',
    trustScore: 7.0,
    scores: { labelAccuracy: 8, dosing: 7, fssai: 8, thirdParty: 7, value: 5 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant via authorized India distributors.',
    thirdPartyTested: true,
    coaPublic: false,
    testingBody: 'NSF Certified for Sport (ISO100 only). Other SKUs not independently certified for the India market.',
    flags: ['premium-price'],
    products: [
      { name: 'ISO100 Hydrolyzed WPI', unit: '1.6 lb', price: 4499, url: 'https://www.amazon.in/s?k=dymatize+iso100+hydrolyzed+whey', lastChecked: 'May 2026' },
    ],
    summary: 'ISO100 is genuinely good — NSF certified, hydrolyzed isolate, clean label. Price-per-gram in India is among the highest in the category. Acceptable for a premium budget; not necessary for most goals.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'fastanup',
    name: 'Fast&Up',
    mark: 'F+',
    markClass: 'mk-amber',
    country: 'India',
    hq: 'Mumbai',
    since: 2015,
    categories: ['vitamins','minerals','amino','preworkout'],
    verdict: 'acceptable',
    trustScore: 6.8,
    scores: { labelAccuracy: 7, dosing: 7, fssai: 9, thirdParty: 5, value: 6 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Effervescent delivery system (Taiyo technology).',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent third-party certification published. Brand claims internal QC.',
    flags: ['premium-price', 'limited-india-testing'],
    products: [
      { name: 'Charge Vitamin C + Zinc', unit: '20 tabs', price: 549, url: 'https://www.amazon.in/s?k=fast+up+charge+vitamin+c+effervescent', lastChecked: 'May 2026' },
      { name: 'Reload Electrolytes', unit: '20 tabs', price: 499, url: 'https://www.amazon.in/s?k=fast+up+reload+electrolytes', lastChecked: 'May 2026' },
    ],
    summary: 'Effervescent delivery is genuinely useful for vitamin C and electrolytes. Vitamin C dose per tab is often below the 1,000 mg therapeutic threshold. Significantly overpriced vs equivalent capsule forms.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'carbamide-forte',
    name: 'Carbamide Forte',
    mark: 'CF',
    markClass: 'mk-amber',
    country: 'India',
    hq: 'Delhi',
    since: 2017,
    categories: ['vitamins','minerals','herbs'],
    verdict: 'acceptable',
    trustScore: 6.8,
    scores: { labelAccuracy: 7, dosing: 7, fssai: 9, thirdParty: 4, value: 8 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Budget-positioned brand with some well-formulated products.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No published third-party COA. Brand claims in-house testing without public disclosure.',
    flags: ['generic-extract', 'no-coa'],
    products: [
      { name: 'Vitamin C 1,000 mg + Zinc', unit: '120 tabs', price: 479, url: 'https://www.amazon.in/s?k=carbamide+forte+vitamin+c+1000mg', lastChecked: 'May 2026' },
      { name: 'Ashwagandha KSM-66 600 mg', unit: '60 caps', price: 449, url: 'https://www.amazon.in/s?k=carbamide+forte+ashwagandha+ksm+66', lastChecked: 'May 2026' },
    ],
    summary: 'Best rupee-per-dose value in the vitamins segment. KSM-66 ashwagandha is correctly labelled — rare in this price range. No public COA is the primary concern; buy for price-sensitive contexts where testing is secondary.',
    reviewUrl: null,
    brandPageUrl: '/brands/carbamide-forte',
    addedDate: '2026-04',
  },

  {
    id: 'labrada',
    name: 'Labrada',
    mark: 'LB',
    markClass: 'mk-blue',
    country: 'USA',
    hq: 'Houston, TX',
    since: 1987,
    categories: ['protein','amino','preworkout'],
    verdict: 'acceptable',
    trustScore: 6.8,
    scores: { labelAccuracy: 7, dosing: 7, fssai: 8, thirdParty: 5, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant. Available via Indian e-commerce.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Some US-market products have prior Informed Sport certification. India-market SKUs not independently certified.',
    flags: [],
    products: [
      { name: 'Lean Body 100% Whey', unit: '2 lb', price: 2999, url: 'https://www.amazon.in/s?k=labrada+lean+body+whey+protein', lastChecked: 'May 2026' },
    ],
    summary: 'Decent transparency and label accuracy. No current independent Indian certification. Verify serving size arithmetic — some SKUs use inflated scoop sizes that reduce effective protein per rupee.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'himalaya',
    name: 'Himalaya Wellness',
    mark: 'HW',
    markClass: 'mk-amber',
    country: 'India',
    hq: 'Bengaluru',
    since: 1930,
    categories: ['herbs','vitamins'],
    verdict: 'acceptable',
    trustScore: 6.5,
    scores: { labelAccuracy: 6, dosing: 6, fssai: 9, thirdParty: 5, value: 8 },
    fssai: true,
    fssaiNote: 'FSSAI + Ayurvedic licensing. Long-standing manufacturer with strong regulatory compliance.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Internal QC only. No independent COA published for supplement line.',
    flags: ['prop-blend', 'generic-extract'],
    products: [
      { name: 'Ashvagandha 250 mg (60 tabs)', unit: '60 tabs', price: 219, url: 'https://www.amazon.in/s?k=himalaya+ashwagandha+tablets', lastChecked: 'May 2026' },
      { name: 'Shilajit Pure Resin (60 caps)', unit: '60 caps', price: 499, url: 'https://www.amazon.in/s?k=himalaya+shilajit', lastChecked: 'May 2026' },
    ],
    summary: 'Generic Withania somnifera powder at low, unstandardised doses — not KSM-66 or Sensoril. Withanolide content not disclosed. Functions as a very-low-dose baseline; not a clinical intervention.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'wellbeing-nutrition',
    name: 'Wellbeing Nutrition',
    mark: 'WN',
    markClass: 'mk-neutral',
    country: 'India',
    hq: 'Mumbai',
    since: 2019,
    categories: ['vitamins','herbs','omega3','preworkout'],
    verdict: 'acceptable',
    trustScore: 6.5,
    scores: { labelAccuracy: 7, dosing: 6, fssai: 9, thirdParty: 5, value: 5 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. D2C premium positioning with oral strip delivery format.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No published independent COA. Brand-commissioned testing claimed without public disclosure.',
    flags: ['premium-price', 'marketing-heavy'],
    products: [
      { name: 'Slow Melts D3 + K2', unit: '60 melts', price: 699, url: 'https://amzn.to/4tDCMkX', lastChecked: 'May 2026' },
      { name: 'Melts Nano Iron', unit: '30 strips', price: 649, url: 'https://www.amazon.in/s?k=wellbeing+nutrition+iron+melts', lastChecked: 'May 2026' },
    ],
    summary: 'Oral strip delivery is genuinely differentiated for iron and B12 (bypasses GI absorption step). D3+K2 product uses correct forms at adequate doses. Significantly overpriced vs capsule equivalents; marketing language overreaches clinical evidence.',
    reviewUrl: '/reviews/vitamins/wellbeing-slow-melts-d3-k2-review',
    brandPageUrl: '/brands/wellbeing-nutrition',
    addedDate: '2026-04',
  },

  {
    id: 'myprotein',
    name: 'MyProtein',
    mark: 'MP',
    markClass: 'mk-blue',
    country: 'UK',
    hq: 'Manchester',
    since: 2004,
    categories: ['protein','amino','vitamins','creatine'],
    verdict: 'acceptable',
    trustScore: 6.5,
    scores: { labelAccuracy: 7, dosing: 7, fssai: 7, thirdParty: 5, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant. Impact Whey is their primary India SKU.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Informed Sport (UK market, specific products). India-market batches not independently certified.',
    flags: ['limited-india-testing'],
    products: [
      { name: 'Impact Whey Protein', unit: '1 kg', price: 1999, url: 'https://www.amazon.in/s?k=myprotein+impact+whey+protein', lastChecked: 'May 2026' },
      { name: 'Creatine Monohydrate Powder', unit: '500 g', price: 799, url: 'https://www.amazon.in/s?k=myprotein+creatine+monohydrate', lastChecked: 'May 2026' },
    ],
    summary: 'Good price-to-protein ratio on Impact Whey. UK Informed Sport status does not automatically apply to India-sold batches. Buy only from MyProtein.in official channel — grey-market units carry adulteration risk.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'scitron',
    name: 'Scitron',
    mark: 'SC',
    markClass: 'mk-amber',
    country: 'India',
    hq: 'Delhi',
    since: 2014,
    categories: ['protein','preworkout','amino'],
    verdict: 'acceptable',
    trustScore: 6.5,
    scores: { labelAccuracy: 7, dosing: 6, fssai: 9, thirdParty: 4, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. India-manufactured protein brand.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Brand-commissioned NABL testing only. No independent blind-purchase COA on record.',
    flags: [],
    products: [
      { name: 'Nitro Series Whey', unit: '1 kg', price: 2199, url: 'https://www.amazon.in/s?k=scitron+nitro+series+whey', lastChecked: 'May 2026' },
      { name: 'Advance Whey', unit: '1 kg', price: 1799, url: 'https://www.amazon.in/s?k=scitron+advance+whey+protein', lastChecked: 'May 2026' },
    ],
    summary: 'Acceptable protein brand with reasonable label honesty. Pre-workout line requires more ingredient-level scrutiny. No independent COA is the primary limiting factor for a higher rating.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'hk-vitals',
    name: 'HK Vitals',
    mark: 'HK',
    markClass: 'mk-neutral',
    country: 'India',
    hq: 'Gurgaon',
    since: 2019,
    categories: ['vitamins','minerals','herbs'],
    verdict: 'acceptable',
    trustScore: 6.4,
    scores: { labelAccuracy: 7, dosing: 6, fssai: 9, thirdParty: 4, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. HealthKart proprietary supplement brand.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent COA. Brand claims internal testing without public documentation.',
    flags: ['generic-extract'],
    products: [
      { name: 'Multivitamin for Men', unit: '60 tabs', price: 399, url: 'https://www.amazon.in/s?k=hk+vitals+multivitamin+men', lastChecked: 'May 2026' },
      { name: 'Biotin 10,000 mcg', unit: '60 tabs', price: 399, url: 'https://www.amazon.in/s?k=hk+vitals+biotin+10000', lastChecked: 'May 2026' },
    ],
    summary: "Base multivitamin uses D2 (ergocalciferol) — a significant form downgrade vs D3. Biotin 10,000 mcg is appropriately dosed. Generic extracts throughout; no patented standardised ingredient use.",
    reviewUrl: '/reviews/multivitamins/hk-vitals-multivitamin-review',
    brandPageUrl: '/brands/hk-vitals',
    addedDate: '2026-04',
  },

  {
    id: 'gnc',
    name: 'GNC',
    mark: 'GC',
    markClass: 'mk-blue',
    country: 'USA',
    hq: 'Pittsburgh, PA',
    since: 1935,
    categories: ['vitamins','protein','amino','preworkout','herbs','omega3'],
    verdict: 'acceptable',
    trustScore: 6.3,
    scores: { labelAccuracy: 6, dosing: 6, fssai: 8, thirdParty: 5, value: 4 },
    fssai: true,
    fssaiNote: 'FSSAI licensed via franchise model. Physical stores + online presence in India.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Some GNC-branded products NSF/BSCG certified in US market. India SKUs not independently certified for domestic market.',
    flags: ['premium-price', 'prop-blend'],
    products: [
      { name: 'Triple Strength Omega-3', unit: '60 softgels', price: 1399, url: 'https://www.amazon.in/s?k=gnc+triple+strength+omega+3', lastChecked: 'May 2026' },
      { name: 'Pro Performance Creatine', unit: '317 g', price: 1299, url: 'https://amzn.to/4tBlvIY', lastChecked: 'May 2026' },
    ],
    summary: 'Brand legacy exceeds current product quality. Price premium is not justified by India-market testing evidence. Omega-3 is correctly dosed; creatine monohydrate is generic at 3× the going domestic rate.',
    reviewUrl: null,
    brandPageUrl: '/brands/gnc-india',
    addedDate: '2026-04',
  },

  {
    id: 'truebasics',
    name: 'TrueBasics',
    mark: 'TB',
    markClass: 'mk-neutral',
    country: 'India',
    hq: 'Gurgaon',
    since: 2016,
    categories: ['vitamins','omega3','protein'],
    verdict: 'acceptable',
    trustScore: 6.0,
    scores: { labelAccuracy: 6, dosing: 6, fssai: 9, thirdParty: 3, value: 6 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. MuscleBlaze / HealthKart sister brand.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No published COA. No Trustified listing. Internal QC claimed.',
    flags: ['underdosed', 'generic-extract', 'no-coa'],
    products: [
      { name: 'Omega-3 Fish Oil', unit: '60 caps', price: 849, url: 'https://www.amazon.in/s?k=truebasics+omega+3+fish+oil', lastChecked: 'May 2026' },
      { name: 'Advanced Multivitamin', unit: '60 tabs', price: 699, url: 'https://www.amazon.in/s?k=truebasics+multivitamin', lastChecked: 'May 2026' },
    ],
    summary: 'Omega-3 adequately dosed (180 EPA + 120 DHA per cap). Multivitamin uses correct D3 form. No public COA and no independent testing remain the primary transparency failures.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'neuherbs',
    name: 'Neuherbs',
    mark: 'NH',
    markClass: 'mk-neutral',
    country: 'India',
    hq: 'Bengaluru',
    since: 2016,
    categories: ['herbs','vitamins','protein'],
    verdict: 'acceptable',
    trustScore: 5.8,
    scores: { labelAccuracy: 6, dosing: 5, fssai: 9, thirdParty: 3, value: 7 },
    fssai: true,
    fssaiNote: 'FSSAI licensed.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent COA or third-party listing. Marketing-first brand.',
    flags: ['marketing-heavy', 'generic-extract', 'no-coa'],
    products: [
      { name: 'True Ashwagandha 600 mg', unit: '60 caps', price: 349, url: 'https://www.amazon.in/s?k=neuherbs+true+ashwagandha', lastChecked: 'May 2026' },
      { name: 'Raw Whey Protein', unit: '1 kg', price: 1699, url: 'https://www.amazon.in/s?k=neuherbs+raw+whey+protein', lastChecked: 'May 2026' },
    ],
    summary: 'Generic Withania somnifera — withanolide percentage not disclosed, not KSM-66 or Sensoril. No independent testing on record. Acceptable only if price is the primary constraint.',
    reviewUrl: null,
    addedDate: '2026-05',
  },

  {
    id: 'bold-care',
    name: 'Bold Care',
    mark: 'BC',
    markClass: 'mk-neutral',
    country: 'India',
    hq: 'Mumbai',
    since: 2020,
    categories: ['herbs','vitamins'],
    verdict: 'acceptable',
    trustScore: 5.8,
    scores: { labelAccuracy: 6, dosing: 5, fssai: 8, thirdParty: 3, value: 5 },
    fssai: true,
    fssaiNote: "FSSAI licensed. Men's health D2C brand.",
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent COA published. Marketing-led positioning.',
    flags: ['marketing-heavy', 'premium-price', 'no-coa'],
    products: [
      { name: "Daily Men's Multivitamin", unit: '60 tabs', price: 699, url: 'https://www.amazon.in/s?k=bold+care+mens+multivitamin', lastChecked: 'May 2026' },
    ],
    summary: "Men's health positioning with strong influencer marketing. Most ingredient doses are sub-clinical. No independent testing published. Premium pricing is not supported by formulation quality.",
    reviewUrl: null,
    addedDate: '2026-05',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // FLAGGED
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  {
    id: 'oziva',
    name: 'OZiva',
    mark: 'OZ',
    markClass: 'mk-red',
    country: 'India',
    hq: 'Mumbai',
    since: 2016,
    categories: ['protein','vitamins','herbs'],
    verdict: 'flagged',
    trustScore: 5.2,
    scores: { labelAccuracy: 5, dosing: 4, fssai: 9, thirdParty: 3, value: 5 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Frequent formulation changes without versioned public changelog.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent COA published. No Trustified listing.',
    flags: ['prop-blend', 'underdosed', 'marketing-heavy', 'generic-extract', 'no-coa'],
    products: [
      { name: 'Plant Protein', unit: '500 g', price: 1399, url: 'https://www.amazon.in/s?k=oziva+plant+protein+powder', lastChecked: 'May 2026' },
      { name: 'HerBalance Multivitamin', unit: '60 caps', price: 799, url: 'https://www.amazon.in/s?k=oziva+herbalance+multivitamin', lastChecked: 'May 2026' },
    ],
    summary: 'Proprietary blends mask individual ingredient doses. Marketing implies clinical-grade evidence with terms like "bioavailable" and "clean label" without supporting COA data. Plant protein cost-per-gram is significantly worse than AS-IT-IS or Nakpro alternatives.',
    reviewUrl: null,
    addedDate: '2026-04',
  },

  {
    id: 'bigmuscles',
    name: 'Bigmuscles Nutrition',
    mark: 'BM',
    markClass: 'mk-red',
    country: 'India',
    hq: 'Delhi',
    since: 2011,
    categories: ['protein','creatine'],
    verdict: 'flagged',
    trustScore: 5.2,
    scores: { labelAccuracy: 5, dosing: 6, fssai: 8, thirdParty: 4, value: 6 },
    fssai: true,
    fssaiNote: 'FSSAI licensed. Informed Choice UK (banned substances only — does NOT verify protein quantity).',
    thirdPartyTested: true,
    coaPublic: true,
    testingBody: 'Brand-commissioned Eurofins (NABL, Pass). Informed Choice UK. NOT independently-initiated blind-purchase testing — a material distinction.',
    flags: ['historical-test-failure', 'brand-coa-only'],
    products: [
      { name: 'Premium Gold Whey', unit: '1 kg', price: 1999, url: 'https://www.amazon.in/s?k=bigmuscles+premium+gold+whey', lastChecked: 'May 2026' },
      { name: 'Real Isolate 90 WPI', unit: '1 kg', price: 2799, url: 'https://www.amazon.in/s?k=bigmuscles+real+isolate+90', lastChecked: 'May 2026' },
    ],
    summary: "Trustified blind-purchase test returned a fail on protein content in 2023. Current brand-commissioned Eurofins reports show Pass. The distinction — brand-commissioned vs independently-initiated — is material. Flagged until an independently-initiated blind-purchase COA is on record.",
    reviewUrl: '/reviews/wheyprotein/bigmuscles-premium-gold-whey-review',
    addedDate: '2026-04',
  },

  {
    id: 'genetic-nutrition',
    name: 'Genetic Nutrition',
    mark: 'GN',
    markClass: 'mk-red',
    country: 'India',
    hq: 'Mumbai',
    since: 2012,
    categories: ['protein','preworkout'],
    verdict: 'flagged',
    trustScore: 4.8,
    scores: { labelAccuracy: 4, dosing: 5, fssai: 6, thirdParty: 2, value: 6 },
    fssai: true,
    fssaiNote: 'FSSAI licensing status not fully confirmed across the complete SKU range.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No published COA. No Trustified or equivalent independent listing on record.',
    flags: ['no-coa', 'label-inflation', 'no-fssai-confirmed'],
    products: [
      { name: 'Iso-Pro Whey Protein', unit: '1 kg', price: 1899, url: 'https://www.amazon.in/s?k=genetic+nutrition+iso+pro+whey', lastChecked: 'May 2026' },
    ],
    summary: 'No public COA, no independent testing, no Trustified listing. Protein-per-serving claims cannot be independently verified. Avoid until verifiable third-party batch testing is published.',
    reviewUrl: null,
    addedDate: '2026-05',
  },

  {
    id: 'musclepharm',
    name: 'MusclePharm',
    mark: 'MP',
    markClass: 'mk-red',
    country: 'USA',
    hq: 'Denver, CO',
    since: 2006,
    categories: ['protein','amino','preworkout'],
    verdict: 'flagged',
    trustScore: 4.5,
    scores: { labelAccuracy: 4, dosing: 4, fssai: 7, thirdParty: 4, value: 5 },
    fssai: true,
    fssaiNote: 'FSSAI import compliant on paper. Brand has documented regulatory actions in USA.',
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'Previous NSF Certified for Sport status lapsed. Current certification status: unverified as of May 2026.',
    flags: ['prop-blend', 'underdosed', 'legal-issues'],
    products: [
      { name: 'Combat 100% Whey', unit: '2 lb', price: 2799, url: 'https://www.amazon.in/s?k=musclepharm+combat+whey+protein', lastChecked: 'May 2026' },
    ],
    summary: 'Documented history of proprietary blends concealing underdosed key ingredients. FTC and SEC regulatory actions on file (US). NSF Certified for Sport status lapsed. Do not purchase until certification is reinstated and independently verified.',
    reviewUrl: null,
    addedDate: '2026-05',
  },

  {
    id: 'himalayan-organics',
    name: 'Himalayan Organics',
    mark: 'HO',
    markClass: 'mk-red',
    country: 'India',
    hq: 'Delhi',
    since: 2017,
    categories: ['herbs','vitamins','omega3'],
    verdict: 'flagged',
    trustScore: 4.8,
    scores: { labelAccuracy: 4, dosing: 4, fssai: 8, thirdParty: 2, value: 6 },
    fssai: true,
    fssaiNote: "FSSAI licensed. 'Organic' labelling not consistently backed by accredited certification.",
    thirdPartyTested: false,
    coaPublic: false,
    testingBody: 'No independent COA published. No third-party listing.',
    flags: ['misleading-claims', 'generic-extract', 'marketing-heavy', 'no-coa'],
    products: [
      { name: 'Plant-Based Omega-3 ALA', unit: '60 caps', price: 799, url: 'https://www.amazon.in/s?k=himalayan+organics+omega+3+plant+based', lastChecked: 'May 2026' },
      { name: 'Ashwagandha 1,000 mg', unit: '60 caps', price: 399, url: 'https://www.amazon.in/s?k=himalayan+organics+ashwagandha', lastChecked: 'May 2026' },
    ],
    summary: 'ALA-only omega-3 product is marketed with language implying equivalence to EPA+DHA fish oil — it is not. ALA→EPA conversion in humans is below 10% in most conditions. Ashwagandha withanolide content and standardisation not disclosed. Misleading organic and plant-based positioning.',
    reviewUrl: null,
    addedDate: '2026-05',
  },

];

// ── Derived stats (used by the page) ───────────────────────────────
const BRANDS_STATS = {
  total: BRANDS_DB.length,
  recommended: BRANDS_DB.filter(b => b.verdict === 'recommended').length,
  acceptable: BRANDS_DB.filter(b => b.verdict === 'acceptable').length,
  flagged: BRANDS_DB.filter(b => b.verdict === 'flagged').length,
  blacklisted: BRANDS_DB.filter(b => b.verdict === 'blacklisted').length,
  lastUpdated: 'May 2026',
};
