#!/usr/bin/env node
/**
 * Naked Compound — sitemap auto-generator
 * Run: node scripts/update-sitemap.js
 * Called by Vercel buildCommand before each deployment.
 *
 * Rules:
 *  - Authoritative domain: https://www.nakedcompound.in  (www-canonical)
 *  - cleanUrls: true  → strip .html from paths
 *  - Exclude: /data/, /uploads/, /assets/, feed.xml, google*.html
 */

const fs   = require('fs');
const path = require('path');

const BASE_URL    = 'https://www.nakedcompound.in';
const OUTPUT_DIR  = path.join(__dirname, '..', 'project');
const SITEMAP_OUT = path.join(OUTPUT_DIR, 'sitemap.xml');
const TODAY       = new Date().toISOString().slice(0, 10);

// ── Priority / changefreq matrix ─────────────────────────────────
const RULES = [
  // path-prefix                       priority  changefreq
  { prefix: '/',                       p: '1.0', cf: 'daily',   exact: true },
  { prefix: '/pages/ingredients/',     p: '0.9', cf: 'weekly' },
  { prefix: '/compare/',               p: '0.8', cf: 'weekly' },
  { prefix: '/pages/best/',            p: '0.8', cf: 'weekly' },
  { prefix: '/research/',              p: '0.8', cf: 'monthly' },
  { prefix: '/pages/research',         p: '0.9', cf: 'weekly',  exact: true },
  { prefix: '/pages/ingredients',      p: '0.9', cf: 'daily',   exact: true },
  { prefix: '/pages/compare',          p: '0.9', cf: 'weekly',  exact: true },
  { prefix: '/pages/blog',             p: '0.8', cf: 'weekly',  exact: true },
  { prefix: '/pages/reviews',          p: '0.8', cf: 'weekly',  exact: true },
  { prefix: '/pages/protocols',        p: '0.8', cf: 'weekly',  exact: true },
  { prefix: '/pages/guides',           p: '0.8', cf: 'weekly',  exact: true },
  { prefix: '/pages/best',             p: '0.8', cf: 'weekly',  exact: true },
  { prefix: '/pages/verified-brands',  p: '0.7', cf: 'monthly', exact: true },
  { prefix: '/pages/learn',            p: '0.7', cf: 'monthly', exact: true },
  { prefix: '/pages/scoring-rubric',   p: '0.7', cf: 'monthly', exact: true },
  { prefix: '/pages/categories',       p: '0.7', cf: 'weekly',  exact: true },
  { prefix: '/protocols/',             p: '0.7', cf: 'monthly' },
  { prefix: '/blog/',                  p: '0.7', cf: 'monthly' },
  { prefix: '/ingredients/',           p: '0.8', cf: 'monthly' },
  { prefix: '/pages/methodology',      p: '0.6', cf: 'monthly', exact: true },
  { prefix: '/pages/about',            p: '0.6', cf: 'monthly', exact: true },
  { prefix: '/pages/authors',          p: '0.6', cf: 'monthly', exact: true },
  { prefix: '/pages/changelog',        p: '0.5', cf: 'weekly',  exact: true },
  { prefix: '/pages/conflicts-policy', p: '0.5', cf: 'monthly', exact: true },
  { prefix: '/pages/contact',          p: '0.4', cf: 'yearly',  exact: true },
  { prefix: '/pages/privacy',          p: '0.2', cf: 'yearly',  exact: true },
  { prefix: '/pages/terms',            p: '0.2', cf: 'yearly',  exact: true },
];

function getPriority(urlPath) {
  // Exact matches first
  for (const r of RULES) {
    if (r.exact && urlPath === r.prefix) return { priority: r.p, changefreq: r.cf };
  }
  // Prefix matches
  for (const r of RULES) {
    if (!r.exact && urlPath.startsWith(r.prefix)) return { priority: r.p, changefreq: r.cf };
  }
  return { priority: '0.5', changefreq: 'monthly' };
}

// ── File discovery ────────────────────────────────────────────────
const EXCLUDE_DIRS  = ['assets', 'data', 'uploads'];
const EXCLUDE_FILES = [/^google[a-z0-9]+\.html$/, /^feed\.xml$/];

function walkDir(dir, base) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const name = entry.name;
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.includes(name)) continue;
      results.push(...walkDir(path.join(dir, name), base));
    } else if (entry.isFile() && name.endsWith('.html')) {
      if (EXCLUDE_FILES.some(re => re.test(name))) continue;
      const abs  = path.join(dir, name);
      const rel  = abs.slice(base.length).replace(/\\/g, '/');
      // Strip .html and /index
      let urlPath = rel.replace(/\.html$/, '').replace(/\/index$/, '');
      if (!urlPath) urlPath = '/';
      results.push(urlPath);
    }
  }
  return results;
}

// ── Build XML ─────────────────────────────────────────────────────
const paths  = walkDir(OUTPUT_DIR, OUTPUT_DIR);
const sorted = [...new Set(paths)].sort((a, b) => {
  // Home first, then by depth, then alpha
  if (a === '/') return -1;
  if (b === '/') return 1;
  const da = (a.match(/\//g) || []).length;
  const db = (b.match(/\//g) || []).length;
  return da - db || a.localeCompare(b);
});

const urlEntries = sorted.map(p => {
  const { priority, changefreq } = getPriority(p);
  const loc = BASE_URL + p;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/update-sitemap.js on ${TODAY} -->
<!-- www-canonical: always use ${BASE_URL}/ -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

${urlEntries}

</urlset>
`;

fs.writeFileSync(SITEMAP_OUT, xml, 'utf8');
console.log(`✓ sitemap.xml written — ${sorted.length} URLs — domain: ${BASE_URL}`);
